/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Certificate = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'created' : Time,
  'year' : IDL.Opt(IDL.Nat),
  'updated' : Time,
  'imageId' : IDL.Opt(IDL.Text),
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'created' : Time,
  'link' : IDL.Opt(IDL.Text),
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'updated' : Time,
  'imageId' : IDL.Opt(IDL.Text),
  'purpose' : IDL.Text,
});
export const Skill = IDL.Record({
  'id' : IDL.Text,
  'created' : Time,
  'name' : IDL.Text,
  'level' : IDL.Opt(IDL.Text),
  'updated' : Time,
  'imageId' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Contact = IDL.Record({
  'linkedin' : IDL.Text,
  'instagram' : IDL.Text,
  'email' : IDL.Text,
  'telegram' : IDL.Text,
});
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'title' : IDL.Text,
  'profileImageId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCertificate' : IDL.Func([Certificate], [], []),
  'addProject' : IDL.Func([Project], [], []),
  'addSkill' : IDL.Func([Skill], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCertificate' : IDL.Func([IDL.Text], [], []),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'deleteSkill' : IDL.Func([IDL.Text], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
  'getContact' : IDL.Func([], [Contact], ['query']),
  'getProfile' : IDL.Func([], [Profile], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateCertificate' : IDL.Func([Certificate], [], []),
  'updateContact' : IDL.Func([Contact], [], []),
  'updateProfile' : IDL.Func([Profile], [], []),
  'updateProject' : IDL.Func([Project], [], []),
  'updateSkill' : IDL.Func([Skill], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Certificate = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'created' : Time,
    'year' : IDL.Opt(IDL.Nat),
    'updated' : Time,
    'imageId' : IDL.Opt(IDL.Text),
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'created' : Time,
    'link' : IDL.Opt(IDL.Text),
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'updated' : Time,
    'imageId' : IDL.Opt(IDL.Text),
    'purpose' : IDL.Text,
  });
  const Skill = IDL.Record({
    'id' : IDL.Text,
    'created' : Time,
    'name' : IDL.Text,
    'level' : IDL.Opt(IDL.Text),
    'updated' : Time,
    'imageId' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Contact = IDL.Record({
    'linkedin' : IDL.Text,
    'instagram' : IDL.Text,
    'email' : IDL.Text,
    'telegram' : IDL.Text,
  });
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'title' : IDL.Text,
    'profileImageId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCertificate' : IDL.Func([Certificate], [], []),
    'addProject' : IDL.Func([Project], [], []),
    'addSkill' : IDL.Func([Skill], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCertificate' : IDL.Func([IDL.Text], [], []),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'deleteSkill' : IDL.Func([IDL.Text], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
    'getContact' : IDL.Func([], [Contact], ['query']),
    'getProfile' : IDL.Func([], [Profile], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateCertificate' : IDL.Func([Certificate], [], []),
    'updateContact' : IDL.Func([Contact], [], []),
    'updateProfile' : IDL.Func([Profile], [], []),
    'updateProject' : IDL.Func([Project], [], []),
    'updateSkill' : IDL.Func([Skill], [], []),
  });
};

export const init = ({ IDL }) => { return []; };