/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Certificate {
  'id' : string,
  'title' : string,
  'created' : Time,
  'year' : [] | [bigint],
  'updated' : Time,
  'imageId' : [] | [string],
}
export interface Contact {
  'linkedin' : string,
  'instagram' : string,
  'email' : string,
  'telegram' : string,
}
export interface Profile {
  'bio' : string,
  'title' : string,
  'profileImageId' : [] | [string],
  'name' : string,
}
export interface Project {
  'id' : string,
  'title' : string,
  'created' : Time,
  'link' : [] | [string],
  'year' : bigint,
  'description' : string,
  'updated' : Time,
  'imageId' : [] | [string],
  'purpose' : string,
}
export interface Skill {
  'id' : string,
  'created' : Time,
  'name' : string,
  'level' : [] | [string],
  'updated' : Time,
  'imageId' : [] | [string],
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCertificate' : ActorMethod<[Certificate], undefined>,
  'addProject' : ActorMethod<[Project], undefined>,
  'addSkill' : ActorMethod<[Skill], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCertificate' : ActorMethod<[string], undefined>,
  'deleteProject' : ActorMethod<[string], undefined>,
  'deleteSkill' : ActorMethod<[string], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCertificates' : ActorMethod<[], Array<Certificate>>,
  'getContact' : ActorMethod<[], Contact>,
  'getProfile' : ActorMethod<[], Profile>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getSkills' : ActorMethod<[], Array<Skill>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateCertificate' : ActorMethod<[Certificate], undefined>,
  'updateContact' : ActorMethod<[Contact], undefined>,
  'updateProfile' : ActorMethod<[Profile], undefined>,
  'updateProject' : ActorMethod<[Project], undefined>,
  'updateSkill' : ActorMethod<[Skill], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];